config/routes.rb
Rails.application.routes.draw do

  scope  "(:locale)", locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars  
    resources :place_rents, only: [:index, :show]

    get '/register', to: 'accounts#new'  
    resources :accounts, except: :new

    get '/login', to: 'sessions#new'
    resource :session, except: :new

    get "/auth/:provider/callback", to: 'sessions#create'
    get "/auth/failure", to: 'sessions#failure'

  end

  root "parkings#index"

end

app/models/place_rent.rb
class PlaceRent < ActiveRecord::Base
  belongs_to :parking
  belongs_to :car
  validates :start_date, :end_date, :parking, :car, presence: true

  before_save :calculate_price
  scope :open_and_future, -> { where("end_date >= ?", DateTime.now) }

  before_create :generate_identifier

  def finish 
    update_attribute(:end_date, DateTime.now)
  end

  def generate_identifier
    self.identifier = SecureRandom.uuid 
  end

  def to_param
    self.identifier
  end

  private 
    def calculate_price
      self.price = parking.day_price.to_i * days_spent + parking.hour_price.to_i * hours_spent
    end

    def days_spent
      (end_date.to_date - start_date.to_date).to_i
    end

    def hours_spent
      ((end_date - start_date)%1.day/3600).ceil
    end

end

app/controllers/place_rents_controller.rb
class PlaceRentsController < ApplicationController
  
  def index
    @place_rents = PlaceRent.all
  end

  def show
    @place_rent = PlaceRent.find_by!(identifier: params[:id])
  end

  def new 
    @place_rent = PlaceRent.new
    @parking =  Parking.find(params[:parking_id])
  end

  def create 
    @place_rent = PlaceRent.new(place_rent_params)
    @place_rent.parking = Parking.find(params[:parking_id])
    
    @place_rent.start_date = parse_date params[:start_date]
    @place_rent.end_date = parse_date params[:end_date]

    if @place_rent.save
      redirect_to @place_rent, notice: "Place rent created successfully."
    else
      render('new')
    end  
  end

  private

    def place_rent_params
      params.require(:place_rent).permit(:start_date, :end_date, :car_id)
    end

    def parse_date main_param
      DateTime.civil(main_param[:year].to_i, main_param[:month].to_i, main_param[:day].to_i, main_param[:hour].to_i, main_param[:minute].to_i)
    end

end

app/views/place_rents/index.html.haml
%h2 Place Rents
%p
%table
  %thead
    %tr
      %th &nbsp;
      %th Start date
      %th &nbsp;
      %th End date
  %tbody
    - @place_rents.each do |place_rent|
      %tr
        %td &nbsp;
        %td= place_rent.start_date
        %th &nbsp;
        %td= place_rent.end_date
        %td=link_to 'Show', place_rent_path(place_rent.identifier)

app/views/place_rents/new.html.erb
<%= link_to("<< Back to List", parkings_path) %>

<div class="place_rents new">
  <h2>Create Place Rent</h2>
  <%= error_messages_for(@place_rent) %>

  <%= form_for [@parking, @place_rent] do |p| %>
  <p>
    <b><%= p.label(:start_date) %></b>
    <%= select_datetime DateTime.now, prefix: :start_date %>
  </p>
  <p>
    <b><%= p.label(:end_date) %></b>
    <%= select_datetime 1.day.from_now, prefix: :end_date %>
  </p>
  <p>
    <b><%= p.label :car %></b>
    <%= p.select(:car_id, options_for_select(current_person.cars.map { |car| [car.model, car.id] })) %>
  </p>

  <p>
    <%= submit_tag("Create Place Rent") %>
  </p>

  <% end %>
</div>

app/views/place_rents/show.html.erb
<div class="place rents show">
  <h2>Show Place Rent</h2>

   <ul>
    <li>Start date: <%= @place_rent.start_date %></li>
    <li>End date: <%= @place_rent.end_date %></li>
  </ul>

</div>