config/routes.rb
Rails.application.routes.draw do

  scope  "(:locale)", locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars  
    resources :place_rents, only: [:index, :show]

    get '/register', to: 'accounts#new'  
    resources :accounts, except: :new

    get '/login', to: 'sessions#new'
    resource :session, except: :new

    get "/auth/:provider/callback", to: 'sessions#create'
    get "/auth/failure", to: 'sessions#failure'

  end

  root "parkings#index"

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  belongs_to :address
  belongs_to :owner, class_name: "Person", foreign_key: "owner_id"
  has_many :place_rents
  KINDS = ['outdoor', 'indoor', 'private', 'street']
  validates :places, :hour_price, :day_price, presence: true
  validates :kind, inclusion: { in: KINDS, :message => "must be one of: #{KINDS.join(', ')}"}
  validates :hour_price, :day_price, :places, :numericality => {:greater_than => 0}
  accepts_nested_attributes_for :address

  before_destroy :finish_rentals

  scope :public_parkings, -> { where("kind IS NOT ?", "private") }
  scope :private_parkings, -> { where(kind: 'private') }
  scope :day_price_within_range, ->  (from, to) { where("day_price between ? and ?", (from || 0), (to || Float::MAX)) }
  scope :hour_price_within_range, -> (from, to) { where("hour_price between ? and ?", (from || 0), (to || Float::MAX)) }
  scope :located_in, -> (city) { joins(:address).where(" addresses.city = ?", city) }

  self.per_page = 5

  def finish_rentals
    place_rents.open_and_future.each(&:finish)
  end

  def self.search(criteria)
    found_parkings = Parking.all
    
    unless criteria[:public].present? && criteria[:private].present?
      if criteria[:private] == "1"
        found_parkings = found_parkings.private_parkings
      end
      if criteria[:public] == "1"
        found_parkings = found_parkings.public_parkings
      end
    end

    if criteria[:location].present?
      found_parkings = found_parkings.located_in(criteria[:location])
    end
    found_parkings = found_parkings.day_price_within_range(criteria[:day_price_min].presence, criteria[:day_price_max].presence)
    found_parkings = found_parkings.hour_price_within_range(criteria[:hour_price_min].presence, criteria[:hour_price_max].presence)
    
    found_parkings
  end

end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  skip_before_action :authenticate_account!

  def index
    @parkings = Parking.search(params).paginate(:page => params[:page], :per_page => Parking.per_page)
  end

  def show
    @parking = Parking.find(params[:id])
  end

  def new 
    @parking = Parking.new
    @parking.build_address
  end

  def create 
    @parking = Parking.new(parking_params)
    @parking.owner = current_person if current_person
    if @parking.save
      redirect_to parkings_path, notice: t('parking_created_success')
    else
      render('new')
    end  
  end

  def edit
    @parking = Parking.find(params[:id])
  end

  def update
    @parking = Parking.find(params[:id])
    if @parking.update_attributes(parking_params)
      redirect_to @parking, notice: t('parking_updated_success')
    else
      render('edit')
    end
  end

  def destroy
    Parking.find(params[:id]).destroy
    redirect_to parkings_path, notice: t('parking_deleted_success')
  end

  private

    def parking_params
      params.require(:parking).permit(:kind, :hour_price, :day_price, :places, 
        address_attributes: [:city, :street, :zip_code] )
    end

end

app/views/parkings/_form.html.erb
<%= error_messages_for(parking) %>

<%= form_for(parking) do |p| %>
  <p>
    <b><%= p.label(:hour_price) %></b>
    <%= p.text_field(:hour_price) %>
  </p>
  <p>
    <b><%= p.label(:day_price) %></b>
    <%= p.text_field(:day_price) %>
  </p>
  <p>
    <b><%= p.label(:places) %></b>
    <%= p.text_field(:places) %>
  </p>
  <p>
    <b><%= p.label(:kind) %></b>
    <%= p.radio_button(:kind, 'outdoor') %><%=  t 'outdoor' %>
    <%= p.radio_button(:kind, 'indoor') %><%= t 'indoor' %>
    <%= p.radio_button(:kind, 'private') %><%= t 'private' %>
    <%= p.radio_button(:kind, 'street') %><%= t 'street' %>
  </p>

  <%= p.fields_for :address do |address_fields| %>
    <p>
      <b><%= address_fields.label(:city) %></b>
      <%= address_fields.text_field(:city) %>
    </p>
    <p>
      <b><%= address_fields.label(:street) %></b>
      <%= address_fields.text_field(:street) %>
    </p>
    <p>
      <b><%= address_fields.label(:zip_code) %></b>
      <%= address_fields.text_field(:zip_code) %>
    </p>
  <% end %>

  <p>
    <%= p.submit %>
  </p>
  
<% end %>

app/views/parkings/edit.html.erb
<%= link_to( t('back'), root_path) %>

<div class="parkings edit">
  <h2><%= t('.update_parking') %></h2>

    <%= render "form", parking: @parking %>

</div>

app/views/parkings/index.html.haml
%h2= t('.parkings')

=link_to t('.add'), new_parking_path

%h3= t('.search')
= form_tag parkings_path, :method => :get  do
  %p 
  = t('kind')
  = check_box_tag(:public, value = "1", checked = false) 
  = label_tag t('public')
  = check_box_tag(:private, value = "1", checked = false) 
  = label_tag t('private')
  %p
  = label_tag(:day_price_range, t('.day_price_range'))
  = label_tag("min:")
  = text_field_tag(:day_price_min)
  = label_tag("max:")
  = text_field_tag(:day_price_max)
  %p
  = label_tag(:hour_price_range, t('.hour_price_range'))
  = label_tag("min:")
  = text_field_tag(:hour_price_min)
  = label_tag("max:") 
  = text_field_tag(:hour_price_max)
  %p
  = label_tag(:location, t('city'))
  = text_field_tag(:location)
  %p
  = submit_tag t('.start_search')

%p
%table
  %thead
    %tr
      %th &nbsp;
      %th= t('city') 
      %th= t('places')
      %th= t('hour_price')
      %th= t('day_price')
  %tbody
    - @parkings.each do |parking|
      %tr
        %td &nbsp;
        %td= parking.address.try(:city)
        %td= parking.places
        %td= parking.hour_price
        %td= parking.day_price
        %td=link_to t('.show'), parking_path(parking), id: "show_#{parking.id}"
        %td &nbsp;
        %td=link_to t('.edit'), edit_parking_path(parking), id: "edit_#{parking.id}"
        %td &nbsp;
        %td=link_to t('.rent'), new_parking_place_rent_url(parking)
        %td &nbsp;
        %td=link_to t('.delete'), parking_path(parking), id: "delete_#{parking.id}", method: :delete, data: { confirm: 'Are you sure?' }

%p= will_paginate @parkings

app/views/parkings/new.html.erb
<%= link_to( t('back'), root_path) %>

<div class="parkings new">
  <h2><%= t '.create_parking' %></h2>

    <%= render "form", parking: @parking %>

</div>

app/views/parkings/show.html.erb
<%= link_to( t('back'), parkings_path )%>

<div class="parkings show">
  <h2><%= t('.show_parking') %></h2>

  <ul>
    <li><b><%= t 'kind' %>:</b> <%= @parking.kind %></li>
    <li><b><%= t 'hour_price' %>:</b> <%= @parking.hour_price %></li>
    <li><b><%= t 'day_price' %>:</b> <%= @parking.day_price %></li>
    <li><b><%= t 'places' %>:</b> <%= @parking.places %></li>
    <p><%= t 'address' %></p>
    <li><b><%= t 'city' %>:</b> <%= @parking.address.city if @parking.address.present? %></li>
    <li><b><%= t 'street' %></b> <%= @parking.address.street if @parking.address.present? %></li>
    <li><b><%= t 'zip_code' %></b> <%= @parking.address.zip_code if @parking.address.present? %></li>
    <li><b><%= t '.owner' %></b> <%= @parking.owner.try(:full_name) %></li>
  </ul>
</div>