config/routes.rb
Rails.application.routes.draw do

  scope  "(:locale)", locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars  
    resources :place_rents, only: [:index, :show]

    get '/register', to: 'accounts#new'  
    resources :accounts, except: :new

    get '/login', to: 'sessions#new'
    resource :session, except: :new

    get "/auth/:provider/callback", to: 'sessions#create'
    get "/auth/failure", to: 'sessions#failure'

  end

  root "parkings#index"

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner, class_name: "Person", foreign_key: "owner_id"
  has_many :place_rents
  validates :registration_number, :model, :owner, presence: true
  validates_size_of :image, maximum: 200.kilobytes
  validates_property :format, of: :image, in: ['jpeg', 'png', 'gif', 'jpg']

  dragonfly_accessor :image

  def to_param
     "#{id}-#{model.parameterize}"
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  def index
    @cars = current_person.try(:cars)
  end

  def show
    @car = current_person.cars.find(params[:id])
  end

  def new 
    @car = current_person.cars.new
  end

  def create 
    @car = Car.new(car_params)
    @car.owner = current_person
    if @car.save
      redirect_to cars_path, notice: "Car created successfully."
    else
      render('new')
    end  
  end

  def edit
    @car = current_person.cars.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update_attributes(car_params)
      redirect_to @car, notice: "Car updated successfully."
    else
      render('edit')
    end
  end

  def destroy
    current_person.cars.find(params[:id]).destroy
    redirect_to cars_path, notice: "Car deleted successfully."
  end

  private

    def car_params
      params.require(:car).permit(:registration_number, :model, :image, :remove_image)
    end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= error_messages_for(car) %>

<%= form_for(car) do |p| %>
  <p>
    <b><%= p.label(:model) %></b>
    <%= p.text_field(:model) %>
  </p>
  <p>
    <b><%= p.label(:registration_number) %></b>
    <%= p.text_field(:registration_number) %>
  </p>

  <p>
    <b><%= p.label :image %></b><%= p.file_field :image %></b>
    <b>Delete image</b>
    <%= p.check_box :remove_image %>
  <p>
    <%= p.submit %>
  </p>
<% end %>

app/views/cars/edit.html.erb
<%= link_to("<< Back to List", cars_path) %>

<div class="cars edit">
  <h2>Update Car</h2>

  <%= render "form", car: @car %>

</div>

app/views/cars/index.html.haml
%h2 Cars
=link_to 'Add New Car', new_car_path
%p
%table
  %thead
    %tr
      %th &nbsp;
      %th Model
      %th Registration number
  %tbody
  - if @cars
    - @cars.each do |car|
      %tr
        %td &nbsp;
        %td= car.model
        %td= car.registration_number
        %td=link_to 'Show', car_path(car), id: "show_#{car.id}"
        %td=link_to 'Edit', edit_car_path(car), id: "edit_#{car.id}"
        %td=link_to 'Delete', car_path(car), id: "delete_#{car.id}", method: :delete, data: { confirm: 'Are you sure?' }

app/views/cars/new.html.erb
<%= link_to("<< Back to List", cars_path) %>

<div class="parkings new">
  <h2>Create Car</h2>

  <%= render "form", car: @car %>
  
</div>

app/views/cars/show.html.erb
<%= link_to("<< Back to List", cars_path) %>

<div class="cars show">
  <h2>Show Car</h2>

  <ul>
    <li><b>Model:</b><%= @car.model %></li>
    <li><b>Registration number:</b><%= @car.registration_number %></li>
    <% if @car.image %>
    <li><b>Image:</b></li>
      <p><%= image_tag @car.image.thumb('400x200').url if @car.image_stored?  %></p>
    <% end %>  
  </ul>
  
</div>