config/routes.rb
Rails.application.routes.draw do

  scope  "(:locale)", locale: /en|pl/ do
    resources :parkings do
      resources :place_rents, only: [:new, :create]
    end

    resources :cars  
    resources :place_rents, only: [:index, :show]

    get '/register', to: 'accounts#new'  
    resources :accounts, except: :new

    get '/login', to: 'sessions#new'
    resource :session, except: :new

    get "/auth/:provider/callback", to: 'sessions#create'
    get "/auth/failure", to: 'sessions#failure'

  end

  root "parkings#index"

end

app/views/layouts/_authentication.html.erb
<%= current_person.full_name if current_person %>

<% if current_person %>
  <%= link_to "Log out", session_path, method: :delete, id: "log_out_link" %>
<% else %>
  <% unless (request.fullpath.match(/login\z/)) || (request.fullpath.match(/register\z/)) %>
    <%= link_to "Log in", login_path %> or <%= link_to "Sign up", register_path %>
  <% end %>
<% end %>

<p><%= link_to "Log in with Facebook", "/auth/facebook" %></p>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= flash_class_name(name) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to "Parkings", parkings_path, class: "label label-warning" %></li>
  <li><%= link_to "Rents", place_rents_path, class: "label label-success" %></li>
  <li><%= link_to "Cars", cars_path, class: "label label-info" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= name_helper  %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <p>
    <%= render "layouts/menu" %>
  </p>
  <p>
    <%= render "layouts/flash" %> 
  </p>
  <p>
    <%= render "layouts/authentication" %>
  </p>

  <%= yield %>
  
</div>

</body>
</html>